=== jrw972/mvolkmann.github.com/bookmarks.dtd
<!ELEMENT bookmarks (topic*)>

<!ELEMENT topic ((topic | mark)*)>
<!ATTLIST topic
  name CDATA #REQUIRED>

<!ELEMENT mark EMPTY>
<!ATTLIST mark
  name CDATA #REQUIRED
  desc CDATA #IMPLIED
  href CDATA #REQUIRED>

=== jrw972/mvolkmann.github.com/bookmarks.xml
<!DOCTYPE bookmarks SYSTEM "bookmarks.dtd">

<bookmarks>

  <topic name="Books">
    <mark name="AbeBooks" href="http://www.abebooks.com"/>
    <mark name="AddALL"
      desc="book search and price comparison"
      href="http://www.addall.com"/>
    <mark name="Amazon" href="http://www.amazon.com"/>
    <mark name="Bartleby" desc="great books online"
      href="http://bartleby.com"/>
    <mark name="Bookpool" href="http://www.bookpool.com"/>
    <mark name="BookServer" href="http://www.archive.org/bookserver"/>
    <mark name="Free Online Books" href="http://pspxworld.com"/>
    <mark name="MySimon" href="http://www.mysimon.com"/>
    <mark name="Nerd Books" href="http://www.nerdbooks.com"/>
    <mark name="Overstock" href="http://www.overstock.com"/>
    <mark name="Pragmatic Bookshelf"
      href="http://www.pragmaticprogrammer.com/bookshelf"/>
  </topic>

  <topic name="Cars">
    <mark name="Kelley Blue Book" href="http://kbb.com"/>
    <mark name="Tire Rack" href="http://www.tirerack.com"/>
    <mark name="True Cost of Ownership"
      href="http://www.edmunds.com/apps/cto/intro.do"/>
  </topic>

  <topic name="Chess">
    <mark name="Jeremy's highest ranking"
      href="http://www.uschess.org/ratings/top/0602/genList.php?filename=18.txt&amp;&amp;pheader=Top%20Age%2018"/>
    <mark name="U.S. Chess Federation" href="http://www.uschess.org"/>
  </topic>

  <topic name="Dogs">
    <mark name="Andauer Whippets"
      href="http://andauerwhippets.tripod.com/"
      desc="owner of Rudy's father, Dominick"/>
    <mark name="Dresslers Dog Supplies"
      href="http://www.dresslersdog.com"/>
    <mark name="Harmony Whippets"
      desc="where we got Rudy"
      href="http://www.harmonywhippets.com"/>
  </topic>

  <topic name="Dictionaries/Encyclopedias">
    <mark name="Dictionary.com" href="http://dictionary.reference.com"/>
    <mark name="Merriam-Webster" href="http://m-w.com"/>
    <mark name="Urban Dictionary" href="http://www.urbandictionary.com"/>
    <mark name="Wikipedia" href="http://www.wikipedia.com"/>
  </topic>

  <topic name="Education">
    <mark name="MIT Open Courseware"
      href="http://ocw.mit.edu/OcwWeb/web/courses/courses/index.htm"/>
    <mark name="MIT video lectures"
      href="http://mitworld.mit.edu/video_index.php"/>
    <mark name="Missouri 529 College Savings Plan (MOST)"
      href="https://missourimost.s.upromise.com/"/>
    <mark name="St. Charles Community College"
      href="http://www.stchas.edu"/>
    <mark name="UC Berkeley lectures"
      href="http://youtube.com/ucberkeley"/>
    <mark name="University of Missouri at Columbia"
      href="http://www.mizzou.edu"/>
    <mark name="University of Missouri at St. Louis"
      href="http://www.umsl.edu"/>
  </topic>

  <topic name="Entertainment">
    <mark name="43 Things"
      href="http://www.43things.com/person/mvolkmann"/>
    <mark name="AMC Theatres"
      href="http://www.amctheatres.com"/>
    <mark name="Criminal Searches" href="http://criminalsearches.com/"/>
    <mark name="This American Life"
      href="http://www.thislife.org"/>
    <mark name="The Bitterest Pill"
      href="http://www.thebitterestpill.com"/>
    <mark name="Internet Movie Database"
      href="http://www.imdb.com"/>
    <mark name="Life in the Office"
      desc="&quot;The Office&quot; inside info., sound clips, quotes and more"
      href="http://www.lifeintheoffice.com"/>
    <mark name="The Office" desc="NBC T.V. show"
      href="http://www.nbc.com/The_Office"/>
    <mark name="Sauce Restaurant Guide"
      href="http://www.saucemagazine.com/restguide.php"/>
    <mark name="Wehernberg Theatres"
      href="http://www.wehrenberg.com"/>
  </topic>

  <topic name="Family">
    <mark name="Richard von Volkmann-Leander"
      href="http://en.wikipedia.org/wiki/Richard_von_Volkmann"/>
  </topic>

  <topic name="File Sharing">
    <mark name="RapidShare" href="http://www.rapidshare.com/"/>
  </topic>

  <topic name="Finance">
    <mark name="Bank of America" href="http://www.bankofamerica.com"/>
    <mark name="Charles Schwab" href="https://www.schwab.com"/>
    <mark name="Discover" href="http://www.discovercard.com"/>
    <mark name="Scottrade" href="http://www.scottrade.com"/>
  </topic>

  <topic name="Humor">
    <mark name="Angry Alien"
      desc="30-second versions of popular movies acted by bunnies"
      href="http://angryalien.com"/>
    <mark name="Church of the Flying Spaghetti Monster"
      href="http://www.venganza.org"/>
    <mark name="Don't Buy Stuff You Cannot Afford"
      href="http://danwho.net/mp/index.php?id=snl_dontbuystuff"/>
    <mark name="Missile Guidance"
      href="http://www.aoe.vt.edu/~cdhall/Space/AFGUID.wav"/>
    <mark name="The Onion"
      href="http://www.onion.com"/>
    <mark name="Housewife Scam"
      href="http://www.theonion.com/content/node/39495"/>
    <mark name="PowerPoint Suicide"
      href="http://www.theonion.com/content/node/30903"/>
  </topic>

  <topic name="Language Translation">
    <mark name="Babel Fish"
      href="http://babelfish.altavista.com/translate.dyn"/>
    <mark name="Google Language Tools"
      href="http://www.google.com/language_tools?hl=en"/>
  </topic>

  <topic name="Macintosh">
    <mark name="Apple Feedback"
      href="http://www.apple.com/feedback"/>
    <mark name="Apple Home"
      href="http://www.apple.com"/>
    <mark name="Cocoa vi Input Manager"
      desc="patches the Cocoa Text System to add a vi-like command mode"
      href="http://www.corsofamily.net/jcorso/vi/"/>
    <mark name="iRed Lite"
      desc="software for Apple Remotes - can control PowerPoint"
      href="http://www.filewell.com/iRedLite/"/>
    <mark name=".Mac Welcome"
      href="http://www.mac.com/WebObjects/Welcome"/>
    <topic name="Quicksilver">
      <mark name="Get To Know"
        href="http://lifehacker.com/software/quicksilver/?view=full"/>
      <mark name="Video Extravaganza"
        href="http://lifehacker.com/software/quicksilver/hack-attack-the-quicksilver-video-extravaganza-250949.php"/>
    </topic>
    <mark name="VersionTracker"
      href="http://www.versiontracker.com/macosx/"/>
  </topic>

  <topic name="Maps">
    <mark name="Google Earth" href="http://earth.google.com"/>
    <mark name="Google Maps" href="http://maps.google.com"/>
    <mark name="MapQuest" href="http://www.mapquest.com"/>
  </topic>

  <topic name="Medical">
    <mark name="Calories Burned Estimator"
      href="http://www.healthstatus.com/calculate/cbc"/>
    <mark name="Mayo Clinic" href="http://www.mayoclinic.com"/>
    <mark name="St. Louis Pollen and Mold"
      href="http://www.stlouisco.com/doh/pollen/Index.cfm"/>
    <mark name="WebMD" href="http://webmd.com"/>
  </topic>

  <topic name="Music">
    <mark name="Deezer" href="http://www.deezer.com"
       desc="listen to full songs for free"/>
    <mark name="Last.fm" href="http://www.last.fm"/>
    <mark name="Pandora" href="http://www.pandora.com/"/>
  </topic>

  <topic name="OCI">
    <mark name="Book Library"
      href="https://internal.ociweb.com/library"/>
    <mark name="CAIT"
      href="http://www.cait.wustl.edu"/>
    <mark name="CAIT Attendance Policy"
        href="https://internal.ociweb.com/CAIT_Attendance_Policy_2008.pdf"/>
    <mark name="Class Schedules"
      href="https://internal.ociweb.com/classSched.pl"/>
    <mark name="Employee Directory"
      href="http://internal.ociweb.com/directory"/>
    <mark name="Employee Handbook"
      href="http://internal.ociweb.com/EmployeeHandbook"/>
    <mark name="Home"
      href="http://www.ociweb.com"/>
    <mark name="JBoss Support"
      href="http://jboss.ociweb.com/support/"/>
    <topic name="JNB">
      <mark name="Articles"
        href="http://www.ociweb.com/articles/publications/jnb.html"/>
      <mark name="Author Guide"
        href="http://www.ociweb.com/jnb/JavaNewsBriefAuthorGuide.html"/>
      <mark name="Schedule"
        href="https://wiki.ociweb.com/wiki/tiki-index.php?page=JavaNewsBriefSchedule"/>
    </topic>
    <mark name="Java Lunch Schedule"
      href="https://wiki.ociweb.com/wiki/tiki-index.php?page=JavaLunchSchedule"/>
    <mark name="Mailing Lists"
      href="https://lists.ociweb.com/mailman/listinfo"/>
    <mark name="Internal/Private"
      href="https://internal.ociweb.com"/>
    <mark name="Project Open"
      href="https://project.ociweb.com"/>
    <mark name="Request Tracker (RT)"
      href="https://support.ociweb.com"/>
    <mark name="Software Development Process"
      desc="(SDP) a local link"
      href="file:///Users/Mark/Documents/OCI/SVN/oci/internal/SDP/OCI_SDP.html"/>
    <mark name="Strategy Wiki"
      href="https://stratwiki.ociweb.com"/>
    <mark name="System Admin. Requests"
      desc="sends email to Chuck Renner and Bill Bird"
      href="mailto:sysadmin-requests@ociweb.com"/>
    <mark name="WebMail"
      href="https://mail.ociweb.com/horde2"/>
    <mark name="Website Statistics"
      desc="username/password in Address Book"
      href="https://ssl.ociweb.com/usage/"/>
    <mark name="Wiki - new"
      href="https://wiki.ociweb.com/wiki/tiki-index.php"/>
    <mark name="Wiki - old"
      href="https://internal.ociweb.com/wiki/oci"/>
  </topic>

  <topic name="Personal Web Sites">
    <mark name="MySpace"
      href="http://www.myspace.com/55880988"/>
    <mark name="Volkmann"
      href="http://webpages.charter.net/volkmann2"/>
    <mark name="Volkmann .Mac"
      href="http://web.mac.com/r.mark.volkmann/iWeb/Site/Welcome.html"/>
    <mark name="Whalen"
      href="http://webpages.charter.net/trwstork"/>
  </topic>

  <topic name="Programming">

    <topic name="Adobe">
      <topic name="ActionScript 3">
        <mark name="Language Reference"
            href="http://livedocs.adobe.com/flash/9.0/ActionScriptLangRefV3/"/>
      </topic>
      <topic name="AIR">
        <mark name="main site" href="http://www.adobe.com/products/air/"/>
        <mark name="Adobe AIR for JavaScript Developers Pocket Guide"
